# Custom image made by Kishan Sambhi
image: gumjoe/wacc-ci-scala:slim

stages:          # List of stages for jobs and their order of execution
  - build
  - testFrontEnd
  - testBackEndIR
  - testExtensions

build:
  stage: build
  script:
    - echo "Building WACC-Compiler..."
    - sbt compile
    - echo "Compile complete"

testFrontEnd:
  stage: testFrontEnd
  script:
    - echo "Testing front-end..."
    - sbt "testOnly *FrontEndTests"
    - echo "Running front-end tests finished"
  environment: production

testIntelX86:
  stage: testBackEndIR
  script:
    - echo "Installing gcc"
    - apt-get update -y
    - apt-get install -y gcc
    - echo "Testing compiler with x86_64 (Intel Syntax) examples..."
    - sbt "testOnly *IntelX86Test"
    - echo "Running compiler with x86_64 (Intel Syntax) examples finished..."
  environment: production

testExtensions:
  stage: testExtensions
  script:
    - echo "Testing standard library extension..."
    - sbt "testOnly *ExtensionTests"
    - echo "Running standard library extension examples finished..."
  environment: production
