# Custom image made by Kishan Sambhi
image: gumjoe/wacc-ci-scala:slim

stages:          # List of stages for jobs and their order of execution
  - build
  - testFrontEnd
  - testIntelX86
  - testBackEndIR

build:
  stage: build
  script:
    - echo "Building WACC-Compiler..."
    - sbt compile
    - echo "Compile complete"

testFrontEnd:
  stage: testFrontEnd
  script:
    - echo "Testing front-end..."
    - sbt "testOnly *FrontEndTests"
    - echo "Running front-end tests finished"
  environment: production

testBackEndIR:
  stage: testBackEndIR
  script:
    - echo "Testing back-end unit tests..."
    - sbt "testOnly *BackendIRTests"
    - echo "Running back-end unit tests finished"
  environment: production

testIntelX86:
  stage: testIntelX86
  script:
    - echo "Installing gcc"
    - apt-get update -y
    - apt-get install -y gcc
    - echo "Testing compiler with x86_64 (Intel Syntax) examples..."
    - sbt "testOnly *IntelX86Test"
    - echo "Running compiler with x86_64 (Intel Syntax) examples finished..."
  environment: production
