# Custom image made by Kishan Sambhi
image: gumjoe/wacc-ci-scala:slim

stages:          # List of stages for jobs and their order of execution
  - build
  - testFrontEnd

build:
  stage: build
  script:
    - echo "Building WACC-Compiler..."
    - sbt compile
    - echo "Compile complete"

testFrontEnd:
  stage: testFrontEnd
  script:
    - echo "Testing front-end..."
    - sbt "testOnly *FrontEndTests"
    - echo "Running front-end tests finished"
  environment: production
