# Custom image made by Kishan Sambhi
image: gumjoe/wacc-ci-scala:slim

stages:          # List of stages for jobs and their order of execution
  - build
  - test

build:
  stage: build
  script:
    - echo "Building WACC-Compiler..."
    - sbt compile
    - echo "Compile complete"

test:
  stage: test
  script: 
      - echo "Running tests..."
      - sbt test
      - echo "All tests finished"
  environment: production
